version: '3'
services:
  httpd:
    build: ./httpd
    ports:
      - "8080:80"
    networks:
      mynetwork:
        ipv4_address: 10.0.0.11
  wildfly1:
    image: jboss/wildfly:13.0.0.Final
    command: /opt/jboss/wildfly/bin/standalone.sh -c standalone-full-ha.xml -b 10.0.0.21 -bmanagement 10.0.0.21
    ports:
      - "8081:8080"
      - "9991:9990"
    networks:
      mynetwork:
        ipv4_address: 10.0.0.21
  wildfly2:
    image: jboss/wildfly:13.0.0.Final
    command: /opt/jboss/wildfly/bin/standalone.sh -c standalone-full-ha.xml -b 10.0.0.22 -bmanagement 10.0.0.22
    ports:
      - "8082:8080"
      - "9992:9990"
    networks:
      mynetwork:
        ipv4_address: 10.0.0.22
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
