version: '3'
services:
  wildfly1:
    image: jboss/wildfly:13.0.0.Final
    ports:
      - "8080:8080"
      - "9990:9990"
  wildfly2:
    image: jboss/wildfly:13.0.0.Final
    ports:
      - "8081:8080"
      - "9991:9990"
