version: '3'
services:
  httpd:
    build: ./httpd
    ports:
      - "8080:80"
      - "6666:6666"
    networks:
      mynetwork:
        ipv4_address: 10.0.0.11
  wildfly1:
    image: yuki/wildfly
    command: /opt/jboss/wildfly/bin/standalone.sh -c standalone-full-ha.xml -b 10.0.0.21 -bmanagement 10.0.0.21
    volumes:
      - "$PWD/wildfly/deployments21:/opt/jboss/wildfly/standalone/deployments"
    ports:
      - "8081:8080"
      - "9991:9990"
    networks:
      mynetwork:
        ipv4_address: 10.0.0.21
  wildfly2:
    image: yuki/wildfly
    command: /opt/jboss/wildfly/bin/standalone.sh -c standalone-full-ha.xml -b 10.0.0.22 -bmanagement 10.0.0.22
    volumes:
      - "$PWD/wildfly/deployments22:/opt/jboss/wildfly/standalone/deployments"
    ports:
      - "8082:8080"
      - "9992:9990"
    networks:
      mynetwork:
        ipv4_address: 10.0.0.22
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
